---
- name: Fetch latest release tag
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ repo_owner }}/{{ repo_name }}/releases/latest"
    return_content: true
  register: api_response
  changed_when: false

- name: Set release version
  ansible.builtin.set_fact:
    release_version: "{{ api_response.json.tag_name }}"