---
- name: Site Playbook
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Print message
      debug:
        msg: |
          Hello! This is the site playbook.
          Please run specific playbooks located in the playbooks/ directory.