---
- name: Site Playbook
  hosts: local

  tasks:
    - name: Check if running on supported OS
      ansible.builtin.assert:
        that:
          - ansible_facts["os_family"] == "Debian"
        fail_msg: "This playbook is only supported on Debian-based systems."

    - name: Display available playbooks
      ansible.builtin.debug:
        msg: "Running all playbooks..."

- name: Import DBeaver playbook
  ansible.builtin.import_playbook: dbeaver.yml

- name: Import Discord playbook
  ansible.builtin.import_playbook: discord.yml

- name: Import LazyGit playbook
  ansible.builtin.import_playbook: lazygit.yml

- name: Import Bruno playbook
  ansible.builtin.import_playbook: bruno.yml