---
- name: Site Playbook
  hosts: local

  tasks:
    - name: Display available playbooks
      ansible.builtin.debug:
        msg: "Running all playbooks..."

- name: Import DBeaver playbook
  ansible.builtin.import_playbook: dbeaver.yml

- name: Import Discord playbook
  ansible.builtin.import_playbook: discord.yml

- name: Import LazyGit playbook
  ansible.builtin.import_playbook: lazygit.yml

- name: Import Bruno playbook
  ansible.builtin.import_playbook: bruno.yml