---
- name: Site Playbook
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Display available playbooks
      ansible.builtin.debug:
        msg: "Running all playbooks..."

- name: Import DBeaver playbook
  ansible.builtin.import_playbook: dbeaver.yml

- name: Import Discord playbook
  ansible.builtin.import_playbook: discord.yml